# coding=utf-8
__author__ = 'Zhang Qifang'

TEST_CMDID = 10000
INVALID_CMDID = 0
REFUSE_CMDID = 1
SEND_DATA_CMDID = 2
RETURN_CMDID = 3
SEND_MESSAGE_CMDID = 4
SEND_FILE_CMDID = 5
LOGIN_CMDID = 6
LOGOUT_CMDID = 7
START_CMDID = 8
HEART_BEAT_CMDID = 9
#------------return code
R_OK = 0
R_INVALID = 1
R_PER = 2
R_CMD=3
R_UNCONNECT=4
R_CONNECT=5
R_POK=6
R_DOK=7
R_BEAT=8

